// fontend/next-version/client/app/san-pham/[slug]/page.tsx
import Link from "next/link";
import BuyButton from "./buy";

export default async function Page({ params }: { params: { slug: string } }) {
  const data = await fetch(`${process.env.BASE_API}/api/product/info`, {
    method: "POST",
    headers: {
      "Content-type": "application/json",
    },
    body: JSON.stringify({
      slug: params.slug,
    }),
    cache: "no-store",
  });
  const { status, data: product } = await data.json();

  const requestRelatedProduct = await fetch(
    `${process.env.BASE_API}/api/product/related`,
    {
      method: "POST",
      headers: {
        "Content-type": "application/json",
      },
      body: JSON.stringify({
        slug: params.slug,
      }),
    }
  );

  const { data: relatedProduct } = await requestRelatedProduct.json();

  return (
    <div className="container mx-auto mt-5">
      <div className="bg-white rounded-md mt-4">
        <div className="grid grid-cols-12 divide-x">
          <div className="col-span-12 xl:col-span-4 lg:col-span-5 md:col-span-4 p-5">
            <img
              src={
                product.images.length
                  ? product.images[0].image_url
                  : "https://i.imgur.com/igbbIRf.png"
              }
              alt=""
              className="rounded-sm w-full aspect-[10/10] object-cover"
            />
            <div className="grid grid-cols-10 mt-4 gap-5">
              {product.images
                ? product.images.map((image: any) => {
                    return (
                      <div className="col-span-2">
                        <img
                          src={image.image_url}
                          alt=""
                          className="object-cover w-full h-full border"
                        />
                      </div>
                    );
                  })
                : ""}
            </div>
          </div>
          <div className="col-span-12 xl:col-span-8 lg:col-span-7 md:col-span-8 p-5">
            <h1 className="text-2xl font-semibold">{product.name}</h1>
            <div className="flex gap-3 mt-2">
              <div className="text-base text-amber-600 font-semibold">
                0.0 <i className="text-xs bi bi-star-fill"></i>
              </div>
              <div className="text-base text-gray-700">(0 đánh giá)</div>
            </div>
            <div className="flex gap-4 mt-5">
              <div className="text-3xl font-semibold text-red-600">
                {(product.price ?? 0).toLocaleString("it-IT", {
                  style: "currency",
                  currency: "VND",
                })}
              </div>
              <span
                className="line-through text-xl text-gray-500 me-3"
                v-if="product?.data.discount"
              >
                {(product.discount ?? 0).toLocaleString("it-IT", {
                  style: "currency",
                  currency: "VND",
                })}
              </span>
              <span
                className="text-red-600 text-sm px-[4px] py-[1px] bg-red-100 border border-red-500 rounded-sm h-fit"
                v-if="product?.data.discount"
              >
                -5%
              </span>
            </div>
            <BuyButton slug={product.slug}></BuyButton>

            {product.short_description ? (
              <div
                className="mt-4 text-lg border-t pt-4"
                dangerouslySetInnerHTML={{ __html: product.short_description }}
              ></div>
            ) : (
              ""
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-12 mt-4 gap-4">
        <div className="col-span-12 md:col-span-8 bg-white rounded-md p-4">
          <h2 className="text-2xl">THÔNG TIN SẢN PHẨM</h2>
          <div className="relative" id="content">
            <div
              dangerouslySetInnerHTML={{ __html: product.description }}
              className="overflow-hidden mt-3"
            ></div>
            {/* <div>
              <div
                className="absolute bottom-10 h-[280px] w-full"
                style={{ background: "" }}
              ></div>
              <div className="absolute w-full text-center py-2 text-blue-600 bg-white bottom-0 text-base cursor-pointer">
                XEM CHI TIẾT
              </div>
            </div> */}
          </div>
        </div>
        <div className="col-span-12 md:col-span-4" id="content-2">
          <div className="sticky top-[95px]">
            <div className="bg-white round-md p-4 h-fit">
              <h2 className="text-2xl">CẤU HÌNH</h2>
              <table className="table w-full border border-collapse mt-3">
                <thead>
                  <tr className="bg-zinc-200">
                    <th className="py-3 px-4">Thẻ</th>
                    <th className="py-3 px-4">Giá trị</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="py-3 px-4">SDD</td>
                    <td className="py-3 px-4">512 GB</td>
                  </tr>
                  <tr>
                    <td className="py-3 px-4">RAM</td>
                    <td className="py-3 px-4">16 GB</td>
                  </tr>
                  <tr className="bg-zinc-200">
                    <td className="py-3 px-4">VGA</td>
                    <td className="py-3 px-4">Onboard</td>
                  </tr>
                  <tr>
                    <td className="py-3 px-4">CPU</td>
                    <td className="py-3 px-4">i5-13500H</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-md mt-4  p-5">
        <h2 className="text-2xl">SẢN PHẨM LIÊN QUAN</h2>
        <div className="grid grid-cols-10 gap-4 rounded-sm mt-3">
          {relatedProduct ? (
            relatedProduct.map((product: any) => {
              return (
                <Link
                  href={`/san-pham/${product.slug}`}
                  className="col-span-2 flex items-center flex-col border cursor-pointer"
                >
                  <img
                    src={
                      product.images && product.images[0]
                        ? product.images[0]["image_url"]
                        : "https://i.imgur.com/igbbIRf.png"
                    }
                    alt=""
                    className="w-full aspect-[10/10] object-contain"
                  />
                  <div className="p-2">
                    <div className="text-start text-md font-semibold line-clamp-2 mb-2">
                      {product.name}
                    </div>
                    <div
                      v-if="product.discount"
                      className="text-sm text-gray-600"
                    >
                      <span className="line-through me-3">
                        {(product.discount ?? 0).toLocaleString("it-IT", {
                          style: "currency",
                          currency: "VND",
                        })}
                      </span>
                      <span
                        v-if="product.discount"
                        className="text-red-600 text-sm px-[4px] py-[1px] bg-red-100 border border-red-500 rounded-sm"
                      >
                        -5%
                      </span>
                    </div>
                    <div className="text-lg font-semibold text-red-600">
                      {(product.price ?? 0).toLocaleString("it-IT", {
                        style: "currency",
                        currency: "VND",
                      })}
                    </div>
                    <div className="flex gap-3 mt-2">
                      <div className="text-sm text-amber-600 font-semibold">
                        {product.avgRating}
                        <i className="text-xs bi bi-star-fill"></i>
                      </div>
                      <div className="text-sm text-gray-700">
                        ({product.totalReviews} đánh giá)
                      </div>
                    </div>
                  </div>
                </Link>
              );
            })
          ) : (
            <div className="col-span-12">Chưa có sản phẩm nào</div>
          )}
        </div>
      </div>
    </div>
  );
}

// fontend/nuxt-version/client/pages/danh-muc/[slug].vue
<template>
  <div>
    <div class="container mx-auto">
      <div class="text-base my-4">
        <el-breadcrumb separator="/">
          <el-breadcrumb-item :to="{ path: '/' }" class="text-base"
            >Trang hủ</el-breadcrumb-item
          >
          <el-breadcrumb-item class="text-base">{{
            request?.data.category.name
          }}</el-breadcrumb-item>
        </el-breadcrumb>
      </div>

      <div
        class="bg-white rounded-md p-4 grid grid-cols-1 xl:grid-cols-5 lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 gap-3 sticky top-[80px] border"
      >
        <Select
          v-model="query.price"
          optionValue="code"
          :options="[
            { name: 'Giá: thấp đến cao', code: 'a-b' },
            { name: 'Giá: cao đến thấp', code: 'b-a' },
          ]"
          optionLabel="name"
          placeholder="Sắp xếp theo giá"
          class="w-full"
        ></Select>
        <div v-for="filter in filtersRequest?.data">
          <MultiSelect
            v-model="selectedFilter[filter.value]"
            :options="filter.values"
            option-label="name"
            option-value="value"
            filter
            :placeholder="filter.name"
            :maxSelectedLabels="3"
            class="w-full"
          />
        </div>

        <div class="flex gap-4">
          <Button
            class="w-full"
            label="LỌC"
            severity="danger"
            @click="onFilter()"
            :loading="status == 'pending' ? true : false"
          ></Button>
          <Button
            class="w-full"
            label="XOÁ LỌC"
            severity="secondary"
            @click="onClearFilter()"
          ></Button>
        </div>
      </div>

      <div class="bg-white rounded-md py-4 shadow-sm mt-4">
        <div
          class="grid grid-cols-1 xl:grid-cols-10 lg:grid-cols-8 md:grid-cols-6 sm:grid-cols-4 gap-4 px-4 rounded-sm"
        >
          <div v-if="!request?.data.products.list.length" class="col-span-12">
            Chưa có sản phẩm nào
          </div>
          <NuxtLink
            :to="`/san-pham/${product.slug}`"
            class="col-span-2 flex items-center flex-col border cursor-pointer"
            v-for="product in request?.data.products.list"
          >
            <img
              :src="product.thumbnail ?? 'https://i.imgur.com/igbbIRf.png'"
              alt=""
              class="w-full aspect-[10/10] object-contain"
            />
            <div class="p-2">
              <div class="text-start text-md font-semibold line-clamp-2 mb-2">
                {{ product.name }}
              </div>
              <div v-if="product.discount" class="text-sm text-gray-600">
                <span class="line-through me-3">
                  {{
                    (product.discount ?? 0).toLocaleString("it-IT", {
                      style: "currency",
                      currency: "VND",
                    })
                  }}
                </span>
                <span
                  v-if="product.discount"
                  class="text-red-600 text-sm px-[4px] py-[1px] bg-red-100 border border-red-500 rounded-sm"
                  >-5%</span
                >
              </div>
              <div class="text-lg font-semibold text-red-600">
                {{
                  (product.price ?? 0).toLocaleString("it-IT", {
                    style: "currency",
                    currency: "VND",
                  })
                }}
              </div>
              <div class="flex gap-3 mt-2">
                <div class="text-sm text-amber-600 font-semibold">
                  0
                  <i class="text-xs bi bi-star-fill"></i>
                </div>
                <div class="text-sm text-gray-700">(0 đánh giá)</div>
              </div>
            </div>
          </NuxtLink>
        </div>
      </div>

      <div
        class="bg-white rounded-md mt-4"
        v-if="request?.data.products.paginate.totalCount"
      >
        <Paginator
          :rows="query.per_page"
          :totalRecords="request?.data.products.paginate.totalCount"
          @page="pageChange"
        ></Paginator>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { PageState } from "primevue/paginator";
import type { ApiResponse, Paginate } from "~/types/ApiReponse";
import type { Categories } from "~/types/category";
import type { Product } from "~/types/product";

const route = useRoute();
const selectedFilter = ref<Record<string, string[]>>({});

const query = reactive<{
  price: string;
  per_page: number;
  page: number;
  filters: string;
}>({
  price: "",
  per_page: 20,
  page: 1,
  filters: "",
});

function convertFiltersToQueryString(
  filters: Record<string, string[]>
): string {
  console.log(filters);

  const queryParts: string[] = [];

  for (const key in filters) {
    if (filters[key] && filters[key].length > 0) {
      queryParts.push(`${key}=${filters[key].join(",")}`);
    }
  }

  return queryParts.join("&");
}

const [{ data: request, refresh, status }, { data: filtersRequest }] =
  await Promise.all([
    eFetch<
      ApiResponse<{
        products: {
          list: Product[];
          paginate: Paginate;
        };
        category: Categories;
      }>
    >(`/api/category/${route.params.slug}`, {
      method: "GET",
      query: query,
      watch: false,
    }),
    eFetch<
      ApiResponse<
        {
          name: string;
          value: string;
          values: {
            name: string;
            value: string;
          }[];
        }[]
      >
    >(`/api/category/${route.params.slug}/filter`, {
      method: "GET",
      watch: false,
    }),
  ]);

function onFilter() {
  query.filters = convertFiltersToQueryString(selectedFilter.value);
  query.page = 1;
  refresh();
}

function onClearFilter() {
  query.page = 1;
  query.per_page = 20;
  query.price = "";
  query.filters = "";
  selectedFilter.value = {};
  refresh();
}

function pageChange(data: PageState) {
  query.page = data.page + 1;
  refresh();
}
</script>

<style scoped></style>
